travis:
  secure:
    BINSTAR_TOKEN: Q2NKV//LXukb9NOMzNSWG8Hzgi8/L4QLK8K6ols66QmFBENNIpRmfk3f1i7m7aeRB3t0mC8oAAIhk6WXo+4v0s4vqSqtcrXGCMub7b+FWmnySrPL9wBeVVfyAgro3JDv+VKZi+Xz1jp2mz4VvcpFBQZ4NM5rcWOjLh0ZQHpo74xXlfjif/H5ytdcB46toVlosWPTUtSJCToy2cBCmbH8bsn9k68+dch7y83qcut5DWJSWbUJaxMji5FRBGWtmdWKFU0dPKqjZqCWOSPVIPZSQRyagi7yyOGP9Y0UuwibIUOd1i7HnQ9R/XYYDyevNEcadwDgXr+BGvGe2ruW2BAS+bwFuTqIdocBN+Ukl0lXEGKnk//a+5TE1eooua95tG4UajGV6jZ8wLQTyNKGVfz+rndqaKkRp1gsqMzykC3pe1wVIuCG9epQUpjJJNPV9sOxkK3wrWjlmcjJgVprJOZdUNgynX9roXX7rxql7X190vxvIZD8GAjZy3S5daOHp7e4kb++APgOO3lsb8sweuFnDwxPVl8Vyq5zqTh/h4GZnpbSpTIZkO4Go9HC34EUQHGRiphMUY0zUGjXsvC/gUOgUDyRODsxJhNxGdOo0uEkURrh6MMDBYSjqO5/gkQbFEk2m1v9wm9kx58ylTydpKMJfJk7sjo1g7l6nNtzlLD7MAo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
