travis:
  secure:
    BINSTAR_TOKEN: ZJ7WorR6PIhP1eMWzl2KVyODEVXV2+EdCuL4YF25Z5elztMzB0NgVVLv10QvBYtlD9JT22wCeMEqJcs3YOzsLX7EhZb3bSc9XOwsk2FQgAqSmd0qGYgnbg00dZMajem3EVZmDz+LZAV+zYLDfXiREX478ArDaO5CmoVYbjIXkkYmOmFP8W4V6+DBGlRxVqU1SAz0RkITP8Z1S587yTJmPLUAJK/B7xYF7YV2aO+2uGV9VUCGwte1kerCfKI/7zxOcxcT91dcIN6G1wNhqkV4e7P+2G2m54GuxJiaJVtWVSlWIZW93i/GOVmnMOfu0V0caEU43Ajp/spkZH4yBkcF2UjEeQt/YmQpW2J9vjiZNuWXd4i5ImCAjToii3Euvr8/oTvHkfunLp02C1apHjAUzbE7v85IItTPQHK8i3JLCW6rBq07W6P5sGYEBfeOT5LvUgLL75YFtcC+oIn932eNLvONwdcIMPMfbjkRKVsTLIPSnX6oqfD32379XbOk47fKgZNclAfmqIxnUHBEiAyS9Q84kfapq6ayqimjz9OjrqRmunXKr4Pr2Hj5GsRN22SrxYQ3LzsZRHYdkt96fdG9Vo3qH/s/8tQWupQ2R0+7dPCHsEgu+O1OoTSobpScjgL984xEI670LLVSONeWm2UL3Bc8lgKemf3DqDlyOsmzjKI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
